//
// Copyright (c) 2024-present Ganbaro Digital Ltd
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
//   * Re-distributions of source code must retain the above copyright
//     notice, this list of conditions and the following disclaimer.
//
//   * Redistributions in binary form must reproduce the above copyright
//     notice, this list of conditions and the following disclaimer in
//     the documentation and/or other materials provided with the
//     distribution.
//
//   * Neither the names of the copyright holders nor the names of his
//     contributors may be used to endorse or promote products derived
//     from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
// COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//

import { makeCssHexColorDefinition, type CssHexColorDefinition } from "@safelytyped/css-color";

export type GanbaroColors = {
    "ganbaro-blue": {
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
        "A100": CssHexColorDefinition,
        "A200": CssHexColorDefinition,
        "A400": CssHexColorDefinition,
        "A700": CssHexColorDefinition,
    },
    "ganbaro-green": {
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
        "A100": CssHexColorDefinition,
        "A200": CssHexColorDefinition,
        "A400": CssHexColorDefinition,
        "A700": CssHexColorDefinition,
    },
    "ganbaro-mono": {
        "0": CssHexColorDefinition,
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
    },
    "ganbaro-orange": {
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
        "A100": CssHexColorDefinition,
        "A200": CssHexColorDefinition,
        "A400": CssHexColorDefinition,
        "A700": CssHexColorDefinition,
    },
    "ganbaro-red": {
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
        "A100": CssHexColorDefinition,
        "A200": CssHexColorDefinition,
        "A400": CssHexColorDefinition,
        "A700": CssHexColorDefinition,
    },
    "ganbaro-slate": {
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
        "A100": CssHexColorDefinition,
        "A200": CssHexColorDefinition,
        "A400": CssHexColorDefinition,
        "A700": CssHexColorDefinition,
    },
    "ganbaro-tan": {
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
        "A100": CssHexColorDefinition,
        "A200": CssHexColorDefinition,
        "A400": CssHexColorDefinition,
        "A700": CssHexColorDefinition,
    },
    "ganbaro-yellow": {
        "50": CssHexColorDefinition,
        "100": CssHexColorDefinition,
        "200": CssHexColorDefinition,
        "300": CssHexColorDefinition,
        "400": CssHexColorDefinition,
        "500": CssHexColorDefinition,
        "600": CssHexColorDefinition,
        "700": CssHexColorDefinition,
        "800": CssHexColorDefinition,
        "900": CssHexColorDefinition,
        "A100": CssHexColorDefinition,
        "A200": CssHexColorDefinition,
        "A400": CssHexColorDefinition,
        "A700": CssHexColorDefinition,
    },
};

export const GANBARO_COLORS: GanbaroColors = {
    "ganbaro-blue": {
        "50": makeCssHexColorDefinition("#b9d0ec"),
        "100": makeCssHexColorDefinition("#91b6e1"),
        "200": makeCssHexColorDefinition("#689bd7"),
        "300": makeCssHexColorDefinition("#4080cc"),
        "400": makeCssHexColorDefinition("#2e67ab"),
        "500": makeCssHexColorDefinition("#234f83"),
        "600": makeCssHexColorDefinition("#1e436f"),
        "700": makeCssHexColorDefinition("#18375b"),
        "800": makeCssHexColorDefinition("#163151"),
        "900": makeCssHexColorDefinition("#132b47"),
        "A100": makeCssHexColorDefinition("#1497fc"),
        "A200": makeCssHexColorDefinition("#108cee"),
        "A400": makeCssHexColorDefinition("#0085e6"),
        "A700": makeCssHexColorDefinition("#0065c1"),
    },
    "ganbaro-green": {
        "50": makeCssHexColorDefinition("#e6f4db"),
        "100": makeCssHexColorDefinition("#ddf0ce"),
        "200": makeCssHexColorDefinition("#d5edc0"),
        "300": makeCssHexColorDefinition("#cce9b3"),
        "400": makeCssHexColorDefinition("#bee3a0"),
        "500": makeCssHexColorDefinition("#b1dd8c"),
        "600": makeCssHexColorDefinition("#96d165"),
        "700": makeCssHexColorDefinition("#7cc63d"),
        "800": makeCssHexColorDefinition("#63a12f"),
        "900": makeCssHexColorDefinition("#4b7924"),
        "A100": makeCssHexColorDefinition("#9dd0a3"),
        "A200": makeCssHexColorDefinition("#94ba9a"),
        "A400": makeCssHexColorDefinition("#6d8f71"),
        "A700": makeCssHexColorDefinition("#075735"),
    },
    "ganbaro-mono": {
        "0": makeCssHexColorDefinition("#fff"),
        "50": makeCssHexColorDefinition("#eee"),
        "100": makeCssHexColorDefinition("#ddd"),
        "200": makeCssHexColorDefinition("#a8a8a8"),
        "300": makeCssHexColorDefinition("#919191"),
        "400": makeCssHexColorDefinition("#7d7d7d"),
        "500": makeCssHexColorDefinition("#696969"),
        "600": makeCssHexColorDefinition("#404040"),
        "700": makeCssHexColorDefinition("#303030"),
        "800": makeCssHexColorDefinition("#222"),
        "900": makeCssHexColorDefinition("#000"),
    },
    "ganbaro-orange": {
        "50": makeCssHexColorDefinition("#ffbe66"),
        "100": makeCssHexColorDefinition("#ffb755"),
        "200": makeCssHexColorDefinition("#ffb044"),
        "300": makeCssHexColorDefinition("#ffa933"),
        "400": makeCssHexColorDefinition("#ff9e1a"),
        "500": makeCssHexColorDefinition("#ff9300"),
        "600": makeCssHexColorDefinition("#e68400"),
        "700": makeCssHexColorDefinition("#cc7600"),
        "800": makeCssHexColorDefinition("#bb6c00"),
        "900": makeCssHexColorDefinition("#aa6200"),
        "A100": makeCssHexColorDefinition("#ffc981"),
        "A200": makeCssHexColorDefinition("#ffb34e"),
        "A400": makeCssHexColorDefinition("#e78400"),
        "A700": makeCssHexColorDefinition("#814a00"),
    },
    "ganbaro-red": {
        "50": makeCssHexColorDefinition("#f8c3c2"),
        "100": makeCssHexColorDefinition("#f5acab"),
        "200": makeCssHexColorDefinition("#ef7f7e"),
        "300": makeCssHexColorDefinition("#ea5250"),
        "400": makeCssHexColorDefinition("#e42523"),
        "500": makeCssHexColorDefinition("#d82726"),
        "600": makeCssHexColorDefinition("#c4201e"),
        "700": makeCssHexColorDefinition("#b11d1b"),
        "800": makeCssHexColorDefinition("#a21b19"),
        "900": makeCssHexColorDefinition("#971817"),
        "A100": makeCssHexColorDefinition("#ffaeac"),
        "A200": makeCssHexColorDefinition("#f26d6b"),
        "A400": makeCssHexColorDefinition("#ec2725"),
        "A700": makeCssHexColorDefinition("#b51110"),
    },
    "ganbaro-slate": {
        "50": makeCssHexColorDefinition("#c3d0da"),
        "100": makeCssHexColorDefinition("#aeb9c3"),
        "200": makeCssHexColorDefinition("#a0abb4"),
        "300": makeCssHexColorDefinition("#919ba3"),
        "400": makeCssHexColorDefinition("#7d858c"),
        "500": makeCssHexColorDefinition("#646b70"),
        "600": makeCssHexColorDefinition("#565c61"),
        "700": makeCssHexColorDefinition("#45494d"),
        "800": makeCssHexColorDefinition("#363a3d"),
        "900": makeCssHexColorDefinition("#242628"),
        "A100": makeCssHexColorDefinition("#b1b9c9"),
        "A200": makeCssHexColorDefinition("#9ea4b3"),
        "A400": makeCssHexColorDefinition("#808591"),
        "A700": makeCssHexColorDefinition("#494c52"),
    },
    "ganbaro-tan": {
        "50": makeCssHexColorDefinition("#ebe7e2"),
        "100": makeCssHexColorDefinition("#dbd7d2"),
        "200": makeCssHexColorDefinition("#aba7a2"),
        "300": makeCssHexColorDefinition("#9b9792"),
        "400": makeCssHexColorDefinition("#7b7772"),
        "500": makeCssHexColorDefinition("#6d6762"),
        "600": makeCssHexColorDefinition("#4b4742"),
        "700": makeCssHexColorDefinition("#3b3732"),
        "800": makeCssHexColorDefinition("#2b2722"),
        "900": makeCssHexColorDefinition("#0b0702"),
        "A100": makeCssHexColorDefinition("#ded9dc"),
        "A200": makeCssHexColorDefinition("#aea9ac"),
        "A400": makeCssHexColorDefinition("#7e797c"),
        "A700": makeCssHexColorDefinition("#3e393c"),
    },
    "ganbaro-yellow": {
        "50": makeCssHexColorDefinition("#fef29a"),
        "100": makeCssHexColorDefinition("#feed72"),
        "200": makeCssHexColorDefinition("#fdeb5d"),
        "300": makeCssHexColorDefinition("#fde949"),
        "400": makeCssHexColorDefinition("#fde635"),
        "500": makeCssHexColorDefinition("#fde11a"),
        "600": makeCssHexColorDefinition("#fcd819"),
        "700": makeCssHexColorDefinition("#fbd113"),
        "800": makeCssHexColorDefinition("#fbc609"),
        "900": makeCssHexColorDefinition("#fcaf19"),
        "A100": makeCssHexColorDefinition("#fff995"),
        "A200": makeCssHexColorDefinition("#fff41f"),
        "A400": makeCssHexColorDefinition("#ffe32d"),
        "A700": makeCssHexColorDefinition("#ffc054"),
    },
};