//
// Copyright (c) 2024-present Ganbaro Digital Ltd
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
//   * Re-distributions of source code must retain the above copyright
//     notice, this list of conditions and the following disclaimer.
//
//   * Redistributions in binary form must reproduce the above copyright
//     notice, this list of conditions and the following disclaimer in
//     the documentation and/or other materials provided with the
//     distribution.
//
//   * Neither the names of the copyright holders nor the names of his
//     contributors may be used to endorse or promote products derived
//     from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
// COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//

import { makeCssHexColorDefinition } from "@safelytyped/css-color";

export const MATERIAL_COLORS = {
    "material-amber": {
        "50": makeCssHexColorDefinition("#fff8e1"),
        "100": makeCssHexColorDefinition("#ffecb3"),
        "200": makeCssHexColorDefinition("#ffe082"),
        "300": makeCssHexColorDefinition("#ffd54f"),
        "400": makeCssHexColorDefinition("#ffca28"),
        "500": makeCssHexColorDefinition("#ffc107"),
        "600": makeCssHexColorDefinition("#ffb300"),
        "700": makeCssHexColorDefinition("#ffa000"),
        "800": makeCssHexColorDefinition("#ff8f00"),
        "900": makeCssHexColorDefinition("#ff6f00"),
        "A100": makeCssHexColorDefinition("#ffe57f"),
        "A200": makeCssHexColorDefinition("#ffd740"),
        "A400": makeCssHexColorDefinition("#ffc400"),
        "A700": makeCssHexColorDefinition("#ffab00"),
    },
    "material-blue": {
        "50": makeCssHexColorDefinition("#e3f2fd"),
        "100": makeCssHexColorDefinition("#bbdefb"),
        "200": makeCssHexColorDefinition("#90caf9"),
        "300": makeCssHexColorDefinition("#64b5f6"),
        "400": makeCssHexColorDefinition("#42a5f5"),
        "500": makeCssHexColorDefinition("#2196f3"),
        "600": makeCssHexColorDefinition("#1e88e5"),
        "700": makeCssHexColorDefinition("#1976d2"),
        "800": makeCssHexColorDefinition("#1565c0"),
        "900": makeCssHexColorDefinition("#0d47a1"),
        "A100": makeCssHexColorDefinition("#82b1ff"),
        "A200": makeCssHexColorDefinition("#448aff"),
        "A400": makeCssHexColorDefinition("#2979ff"),
        "A700": makeCssHexColorDefinition("#2962ff"),
    },
    "material-bluegray": {
        "50": makeCssHexColorDefinition("#eceff1"),
        "100": makeCssHexColorDefinition("#cfd8dc"),
        "200": makeCssHexColorDefinition("#b0bec5"),
        "300": makeCssHexColorDefinition("#90a4ae"),
        "400": makeCssHexColorDefinition("#78909c"),
        "500": makeCssHexColorDefinition("#607d8b"),
        "600": makeCssHexColorDefinition("#546e7a"),
        "700": makeCssHexColorDefinition("#455a64"),
        "800": makeCssHexColorDefinition("#37474f"),
        "900": makeCssHexColorDefinition("#263238"),
    },
    "material-brown": {
        "50": makeCssHexColorDefinition("#efebe9"),
        "100": makeCssHexColorDefinition("#d7ccc8"),
        "200": makeCssHexColorDefinition("#bcaaa4"),
        "300": makeCssHexColorDefinition("#a1887f"),
        "400": makeCssHexColorDefinition("#8d6e63"),
        "500": makeCssHexColorDefinition("#795548"),
        "600": makeCssHexColorDefinition("#6d4c41"),
        "700": makeCssHexColorDefinition("#5d4037"),
        "800": makeCssHexColorDefinition("#4e342e"),
        "900": makeCssHexColorDefinition("#3e2723"),
    },
    "material-cyan": {
        "50": makeCssHexColorDefinition("#e0f7fa"),
        "100": makeCssHexColorDefinition("#b2ebf2"),
        "200": makeCssHexColorDefinition("#80deea"),
        "300": makeCssHexColorDefinition("#4dd0e1"),
        "400": makeCssHexColorDefinition("#26c6da"),
        "500": makeCssHexColorDefinition("#00bcd4"),
        "600": makeCssHexColorDefinition("#00acc1"),
        "700": makeCssHexColorDefinition("#0097a7"),
        "800": makeCssHexColorDefinition("#00838f"),
        "900": makeCssHexColorDefinition("#006064"),
        "A100": makeCssHexColorDefinition("#84ffff"),
        "A200": makeCssHexColorDefinition("#18ffff"),
        "A400": makeCssHexColorDefinition("#00e5ff"),
        "A700": makeCssHexColorDefinition("#00b8d4"),
    },
    "material-deeporange": {
        "50": makeCssHexColorDefinition("#fbe9e7"),
        "100": makeCssHexColorDefinition("#ffccbc"),
        "200": makeCssHexColorDefinition("#ffab91"),
        "300": makeCssHexColorDefinition("#ff8a65"),
        "400": makeCssHexColorDefinition("#ff7043"),
        "500": makeCssHexColorDefinition("#ff5722"),
        "600": makeCssHexColorDefinition("#f4511e"),
        "700": makeCssHexColorDefinition("#e64a19"),
        "800": makeCssHexColorDefinition("#d84315"),
        "900": makeCssHexColorDefinition("#bf360c"),
        "A100": makeCssHexColorDefinition("#ff9e80"),
        "A200": makeCssHexColorDefinition("#ff6e40"),
        "A400": makeCssHexColorDefinition("#ff3d00"),
        "A700": makeCssHexColorDefinition("#dd2c00"),
    },
    "material-deeppurple": {
        "50": makeCssHexColorDefinition("#ede7f6"),
        "100": makeCssHexColorDefinition("#d1c4e9"),
        "200": makeCssHexColorDefinition("#b39ddb"),
        "300": makeCssHexColorDefinition("#9575cd"),
        "400": makeCssHexColorDefinition("#7e57c2"),
        "500": makeCssHexColorDefinition("#673ab7"),
        "600": makeCssHexColorDefinition("#5e35b1"),
        "700": makeCssHexColorDefinition("#512da8"),
        "800": makeCssHexColorDefinition("#4527a0"),
        "900": makeCssHexColorDefinition("#311b92"),
        "A100": makeCssHexColorDefinition("#b388ff"),
        "A200": makeCssHexColorDefinition("#7c4dff"),
        "A400": makeCssHexColorDefinition("#651fff"),
        "A700": makeCssHexColorDefinition("#6200ea"),
    },
    "material-gray": {
        "50": makeCssHexColorDefinition("#fafafa"),
        "100": makeCssHexColorDefinition("#f5f5f5"),
        "200": makeCssHexColorDefinition("#eee"),
        "300": makeCssHexColorDefinition("#e0e0e0"),
        "400": makeCssHexColorDefinition("#bdbdbd"),
        "500": makeCssHexColorDefinition("#9e9e9e"),
        "600": makeCssHexColorDefinition("#757575"),
        "700": makeCssHexColorDefinition("#616161"),
        "800": makeCssHexColorDefinition("#424242"),
        "900": makeCssHexColorDefinition("#212121"),
    },
    "material-green": {
        "50": makeCssHexColorDefinition("#e8f5e9"),
        "100": makeCssHexColorDefinition("#c8e6c9"),
        "200": makeCssHexColorDefinition("#a5d6a7"),
        "300": makeCssHexColorDefinition("#81c784"),
        "400": makeCssHexColorDefinition("#66bb6a"),
        "500": makeCssHexColorDefinition("#4caf50"),
        "600": makeCssHexColorDefinition("#43a047"),
        "700": makeCssHexColorDefinition("#388e3c"),
        "800": makeCssHexColorDefinition("#2e7d32"),
        "900": makeCssHexColorDefinition("#1b5e20"),
        "A100": makeCssHexColorDefinition("#b9f6ca"),
        "A200": makeCssHexColorDefinition("#69f0ae"),
        "A400": makeCssHexColorDefinition("#00e676"),
        "A700": makeCssHexColorDefinition("#00c853"),
    },
    "material-indigo": {
        "50": makeCssHexColorDefinition("#e8eaf6"),
        "100": makeCssHexColorDefinition("#c5cae9"),
        "200": makeCssHexColorDefinition("#9fa8da"),
        "300": makeCssHexColorDefinition("#7986cb"),
        "400": makeCssHexColorDefinition("#5c6bc0"),
        "500": makeCssHexColorDefinition("#3f51b5"),
        "600": makeCssHexColorDefinition("#3949ab"),
        "700": makeCssHexColorDefinition("#303f9f"),
        "800": makeCssHexColorDefinition("#283593"),
        "900": makeCssHexColorDefinition("#1a237e"),
        "A100": makeCssHexColorDefinition("#8c9eff"),
        "A200": makeCssHexColorDefinition("#536dfe"),
        "A400": makeCssHexColorDefinition("#3d5afe"),
        "A700": makeCssHexColorDefinition("#304ffe"),
    },
    "material-lightblue": {
        "50": makeCssHexColorDefinition("#e1f5fe"),
        "100": makeCssHexColorDefinition("#b3e5fc"),
        "200": makeCssHexColorDefinition("#81d4fa"),
        "300": makeCssHexColorDefinition("#4fc3f7"),
        "400": makeCssHexColorDefinition("#29b6f6"),
        "500": makeCssHexColorDefinition("#03a9f4"),
        "600": makeCssHexColorDefinition("#039be5"),
        "700": makeCssHexColorDefinition("#0288d1"),
        "800": makeCssHexColorDefinition("#0277bd"),
        "900": makeCssHexColorDefinition("#01579b"),
        "A100": makeCssHexColorDefinition("#80d8ff"),
        "A200": makeCssHexColorDefinition("#40c4ff"),
        "A400": makeCssHexColorDefinition("#00b0ff"),
        "A700": makeCssHexColorDefinition("#0091ea"),
    },
    "material-lightgreen": {
        "50": makeCssHexColorDefinition("#f1f8e9"),
        "100": makeCssHexColorDefinition("#dcedc8"),
        "200": makeCssHexColorDefinition("#c5e1a5"),
        "300": makeCssHexColorDefinition("#aed581"),
        "400": makeCssHexColorDefinition("#9ccc65"),
        "500": makeCssHexColorDefinition("#8bc34a"),
        "600": makeCssHexColorDefinition("#7cb342"),
        "700": makeCssHexColorDefinition("#689f38"),
        "800": makeCssHexColorDefinition("#558b2f"),
        "900": makeCssHexColorDefinition("#33691e"),
        "A100": makeCssHexColorDefinition("#ccff90"),
        "A200": makeCssHexColorDefinition("#b2ff59"),
        "A400": makeCssHexColorDefinition("#76ff03"),
        "A700": makeCssHexColorDefinition("#64dd17"),
    },
    "material-lime": {
        "50": makeCssHexColorDefinition("#f9fbe7"),
        "100": makeCssHexColorDefinition("#f0f4c3"),
        "200": makeCssHexColorDefinition("#e6ee9c"),
        "300": makeCssHexColorDefinition("#dce775"),
        "400": makeCssHexColorDefinition("#d4e157"),
        "500": makeCssHexColorDefinition("#cddc39"),
        "600": makeCssHexColorDefinition("#c0ca33"),
        "700": makeCssHexColorDefinition("#afb42b"),
        "800": makeCssHexColorDefinition("#9e9d24"),
        "900": makeCssHexColorDefinition("#827717"),
        "A100": makeCssHexColorDefinition("#f4ff81"),
        "A200": makeCssHexColorDefinition("#eeff41"),
        "A400": makeCssHexColorDefinition("#c6ff00"),
        "A700": makeCssHexColorDefinition("#aeea00"),
    },
    "material-orange": {
        "50": makeCssHexColorDefinition("#fff3e0"),
        "100": makeCssHexColorDefinition("#ffe0b2"),
        "200": makeCssHexColorDefinition("#ffcc80"),
        "300": makeCssHexColorDefinition("#ffb74d"),
        "400": makeCssHexColorDefinition("#ffa726"),
        "500": makeCssHexColorDefinition("#ff9800"),
        "600": makeCssHexColorDefinition("#fb8c00"),
        "700": makeCssHexColorDefinition("#f57c00"),
        "800": makeCssHexColorDefinition("#ef6c00"),
        "900": makeCssHexColorDefinition("#e65100"),
        "A100": makeCssHexColorDefinition("#ffd180"),
        "A200": makeCssHexColorDefinition("#ffab40"),
        "A400": makeCssHexColorDefinition("#ff9100"),
        "A700": makeCssHexColorDefinition("#ff6d00"),
    },
    "material-pink": {
        "50": makeCssHexColorDefinition("#fce4ec"),
        "100": makeCssHexColorDefinition("#f8bbd0"),
        "200": makeCssHexColorDefinition("#f48fb1"),
        "300": makeCssHexColorDefinition("#f06292"),
        "400": makeCssHexColorDefinition("#ec407a"),
        "500": makeCssHexColorDefinition("#e91e63"),
        "600": makeCssHexColorDefinition("#d81b60"),
        "700": makeCssHexColorDefinition("#c2185b"),
        "800": makeCssHexColorDefinition("#ad1457"),
        "900": makeCssHexColorDefinition("#880e4f"),
        "A100": makeCssHexColorDefinition("#ff80ab"),
        "A200": makeCssHexColorDefinition("#ff4081"),
        "A400": makeCssHexColorDefinition("#f50057"),
        "A700": makeCssHexColorDefinition("#c51162"),
    },
    "material-purple": {
        "50": makeCssHexColorDefinition("#f3e5f5"),
        "100": makeCssHexColorDefinition("#e1bee7"),
        "200": makeCssHexColorDefinition("#ce93d8"),
        "300": makeCssHexColorDefinition("#ba68c8"),
        "400": makeCssHexColorDefinition("#ab47bc"),
        "500": makeCssHexColorDefinition("#9c27b0"),
        "600": makeCssHexColorDefinition("#8e24aa"),
        "700": makeCssHexColorDefinition("#7b1fa2"),
        "800": makeCssHexColorDefinition("#6a1b9a"),
        "900": makeCssHexColorDefinition("#4a148c"),
        "A100": makeCssHexColorDefinition("#ea80fc"),
        "A200": makeCssHexColorDefinition("#e040fb"),
        "A400": makeCssHexColorDefinition("#d500f9"),
        "A700": makeCssHexColorDefinition("#a0f"),
    },
    "material-red": {
        "50": makeCssHexColorDefinition("#ffebee"),
        "100": makeCssHexColorDefinition("#ffcdd2"),
        "200": makeCssHexColorDefinition("#ef9a9a"),
        "300": makeCssHexColorDefinition("#e57373"),
        "400": makeCssHexColorDefinition("#ef5350"),
        "500": makeCssHexColorDefinition("#f44336"),
        "600": makeCssHexColorDefinition("#e53935"),
        "700": makeCssHexColorDefinition("#d32f2f"),
        "800": makeCssHexColorDefinition("#c62828"),
        "900": makeCssHexColorDefinition("#b71c1c"),
        "A100": makeCssHexColorDefinition("#ff8a80"),
        "A200": makeCssHexColorDefinition("#ff5252"),
        "A400": makeCssHexColorDefinition("#ff1744"),
        "A700": makeCssHexColorDefinition("#d50000"),
    },
    "material-teal": {
        "50": makeCssHexColorDefinition("#e0f2f1"),
        "100": makeCssHexColorDefinition("#b2dfdb"),
        "200": makeCssHexColorDefinition("#80cbc4"),
        "300": makeCssHexColorDefinition("#4db6ac"),
        "400": makeCssHexColorDefinition("#26a69a"),
        "500": makeCssHexColorDefinition("#009688"),
        "600": makeCssHexColorDefinition("#00897b"),
        "700": makeCssHexColorDefinition("#00796b"),
        "800": makeCssHexColorDefinition("#00695c"),
        "900": makeCssHexColorDefinition("#004d40"),
        "A100": makeCssHexColorDefinition("#a7ffeb"),
        "A200": makeCssHexColorDefinition("#64ffda"),
        "A400": makeCssHexColorDefinition("#1de9b6"),
        "A700": makeCssHexColorDefinition("#00bfa5"),
    },
    "material-yellow": {
        "50": makeCssHexColorDefinition("#fffde7"),
        "100": makeCssHexColorDefinition("#fff9c4"),
        "200": makeCssHexColorDefinition("#fff59d"),
        "300": makeCssHexColorDefinition("#fff176"),
        "400": makeCssHexColorDefinition("#ffee58"),
        "500": makeCssHexColorDefinition("#ffeb3b"),
        "600": makeCssHexColorDefinition("#fdd835"),
        "700": makeCssHexColorDefinition("#fbc02d"),
        "800": makeCssHexColorDefinition("#f9a825"),
        "900": makeCssHexColorDefinition("#f57f17"),
        "A100": makeCssHexColorDefinition("#ffff8d"),
        "A200": makeCssHexColorDefinition("#ff0"),
        "A400": makeCssHexColorDefinition("#ffea00"),
        "A700": makeCssHexColorDefinition("#ffd600"),
    },
};