module.exports = {
    'imprint-black': '#000',
    'imprint-carbon': '#303030',
    'imprint-darkblue': '#234f83',
    'imprint-darkgreen': '#3c763d',
    'imprint-darkred': '#a94442',
    'imprint-darkyellow': '#e8ca2b',
    'imprint-darkgray': '#696969',
    'imprint-graphite': '#404040',
    'imprint-gray': '#a8a8a8',
    'imprint-lightblue': '#34789a',
    'imprint-lightgray': '#ddd',
    'imprint-lightred': '#f2dede',
    'imprint-nero': '#222',
    'imprint-paleblue': '#f4f8fa',
    'imprint-palegray': '#eee',
    'imprint-palegreen': '#dff0d8',
    'imprint-palered': '#f9f2f4',
    'imprint-paleyellow': '#fcf8e3',
    'imprint-red': '#c7254e',
    'imprint-white': '#fff',
};